### ISSUE TITLE
Coderdojo

### ISSUE THREAD

**Issue by ipersoft** [comune-desio/wiki#3]
[Creare un Coderdojo](http://www.coderdojoitalia.org/far-partire-un-dojo/)

**Comment by olistik** [comment]
@ipersoft in seguito ad una segnalazione di @sarm0n ho creato un'attività simile qui: https://github.com/open-comune/desio/issues/15
Una delle prime attività è _Trovare una persona di riferimento (il Champion)_, te saresti disponibile? :-)

**Comment by ipersoft** [comment]
Fare da Champion mi sembra un po' impegnativo senza una esperienza sul campo. Se riusciamo ad affiancarci ad un gruppo già costituito preferirei.

**Comment by olistik** [comment]
@ipersoft intanto, lasciamo la issue qua o la spostiamo nel contenitore di Open Desio?

**Comment by ipersoft** [comment]
@olistik se è una iniziativa che non parte da qua spostala di la ;-)

**Comment by olistik** [comment]
Chiudo qua :-)
